[project]
name = "rag-against-the-machine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fire>=0.7.1",
    "flake8>=7.3.0",
    "icecream>=2.2.0",
    "mypy>=2.3.1",
    "pre-commit>=4.6.2",
    "pydantic>=2.13.5",
    "rank-bm25>=0.2.2",
    "tqdm>=4.70.0",
    "tree-sitter>=0.26.0",
    "tree-sitter-python>=0.25.0",
]
