"""Pydantic models for the index, the datasets and the JSON result files."""
from pydantic import BaseModel, Field
import uuid


class MinimalSource(BaseModel):
    """Span of a corpus file that a chunk or a reference answer points to.

    Attributes:
        file_path: Path of the file, relative to the project root.
        first_character_index: Offset where the span starts.
        last_character_index: Offset where the span ends (exclusive, as in
            a Python slice).
    """

    file_path: str
    first_character_index: int
    last_character_index: int


class UnansweredQuestion(BaseModel):
    """Dataset question without a reference answer.

    Attributes:
        question_id: Unique id of the question. A random UUID is generated
            if the JSON does not provide one.
        question: Text of the question.
    """

    question_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    question: str


class AnsweredQuestion(UnansweredQuestion):
    """Dataset question with its reference answer and sources.

    Attributes:
        sources: Spans of the corpus that contain the answer. The evaluator
            compares retrieved chunks against them.
        answer: Reference answer text.
    """

    sources: list[MinimalSource]
    answer: str


class RagDataset(BaseModel):
    """Question dataset, read by ``search_dataset`` and ``evaluate``."""

    rag_questions: list[AnsweredQuestion | UnansweredQuestion]


class MinimalSearchResults(BaseModel):
    """Retrieval result for one question.

    Attributes:
        question_id: Id of the question in the dataset.
        question: Text of the question.
        retrieved_sources: Retrieved chunks, best-scored first.
    """

    question_id: str
    question: str
    retrieved_sources: list[MinimalSource]


class MinimalAnswer(MinimalSearchResults):
    """Generated answer for one question.

    Here ``retrieved_sources`` holds only the chunks given to the LLM as
    context, not every chunk retrieved.

    Attributes:
        answer: Text generated by the LLM.
    """

    answer: str


class StudentSearchResults(BaseModel):
    """Content of the file written by ``search_dataset``.

    Attributes:
        search_results: One entry per dataset question.
        k: Number of chunks retrieved per question.
    """

    search_results: list[MinimalSearchResults]
    k: int


class StudentSearchResultsAndAnswer(BaseModel):
    """Content of the file written by ``answer_dataset``.

    Attributes:
        search_results: One answer per question in the search-results file.
        k: Number of chunks used as context per question.
    """

    search_results: list[MinimalAnswer]
    k: int


class IndexedChunk(BaseModel):
    """Chunk of a corpus file, as stored in the chunks JSON file.

    Attributes:
        text: Content of the chunk, with surrounding whitespace stripped.
        metadata: Location of the chunk in its file.
    """

    text: str
    metadata: MinimalSource


class RagIndex(BaseModel):
    """Every chunk of the corpus.

    The order of ``chunks`` matches the BM25 index: the n-th chunk is the
    n-th document scored by BM25.
    """

    chunks: list[IndexedChunk]
